### ISSUE TITLE
Get rid of vault in enrich_values method

### ISSUE THREAD

**Issue by artem-v** [scalecube/spinless#17]
Subj.

- [x] In function `enrich_values_yaml`: 
```python
        vault = Vault(logger=self.logger,
                      owner=self.owner,
                      repo=self.repo,
                      branch_name=self.branch_name,
                      )
```
This `vault` dependency is not needed. We decided not to pull vaules from Vault in order to put them into .vaules file, because if pod would have access to Vault it will get needed vaules un runtime.

- [x] Fix a `todo` comment: 
```
        ### Remove create role
        vault.create_role()
```
Indeed  removed create_role from this method, and use it in the context of `install_package`.  NOTE: this `.create_role()` must be called before `helm install`.

**Comment by snripa** [comment]
what if helm install failed? remove role?
