### ISSUE TITLE
namespaces REST API

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/spinless#35]
when closing a pull request we should delete the namespaces and free resources:
```
DELETE /kubernetes/cluster_name/namespaces/<namespace>
```

Response:
```
{"job_id": "xxxxxxxxx"}
```

----------

to sync between current active namespaces vs opened pull requests we need a list 
```
GET /kubernetes/cluster_name/namespaces/
```

Response:
```
[
 "develop",
 "master",
 "scalecube-seed-42"
]
```

**Comment by snripa** [comment]
Done
