### ISSUE TITLE
New pods are not starting automatically

### ISSUE THREAD

**Issue by segabriel** [scalecube/spinless#43]
Time to time we have an issue when the spinless received the needed request and applied it, but old pods were keeping in `Running` state, and new pods were staying in `ContainerCreating` state. And for some reason I had to remove old replicasets manually.

Could you recheck and investigate your helm commands? And maybe add notifications about some conflicts. Now it's a black box.

**Comment by ronenhamias** [comment]
helm upgrade install command is pretty standard 
can you please provide more details why the container was not creating?

https://helm.sh/docs/helm/helm_upgrade/

**Comment by segabriel** [comment]
> can you please provide more details why the container was not creating?

Unfortunately not, I am not DevOps, and I don't know where logs of spinless.

**Comment by snripa** [comment]
helm command is printed in logs per every deployment - you can find it in logs.
```
helm_install_cmd = [helm_cmd, "upgrade",
                            f'{self.owner}-{self.repo}-{self.branch}',
                            f'{self.helm_dir}/{self.repo}',
                            "--debug", "--install", "--namespace", self.namespace,
                            "-f", path_to_values_yaml,
                            ]
```

As you see, helm command is quite straightforward.

If you would had managed to fix your issue just with manual execution of helm command, we'd look into this problem.

But as long as proper command (with correct values-spinless.yaml) was executed, spinless can't do more.

**Comment by ronenhamias** [comment]
please provide more details for this issue.

> > can you please provide more details why the container was not creating?
> 
> Unfortunately not, I am not DevOps, and I don't know where logs of spinless.

the "logs" are in the check run status. printed out to github they also appear in loki.

can you please look into k8s logs and check why container didnt start and attach this to this issue?

For you convinance here is the helm command:

```
/usr/local/bin/helm upgrade <your-artifact-name> ./state/pkg/1590140302173/<your-artifact-name> --debug --install --namespace master -f ./state/pkg/1590140302173/spinless-values.yaml --set dockerjsontoken=.....
```
please point what is the issue.

thanks.

**Comment by ronenhamias** [comment]
closing this issue due to lack of information.
